"""Format registry, capabilities, and alias normalization for 70+ image formats."""

from typing import Dict, List, Optional
from image_converter.models import FormatInfo
from image_converter.exceptions import UnsupportedFormatError

# Canonical Format Registry
FORMAT_REGISTRY: Dict[str, FormatInfo] = {
    # --- Standard Pillow-Supported Formats ---
    "PNG": FormatInfo(
        canonical_name="PNG",
        extensions=[".png"],
        mime_type="image/png",
        backend="pillow",
        supports_alpha=True,
        supports_animation=True,  # APNG
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PNG",
        description="Portable Network Graphics",
        allowed_modes=["1", "L", "LA", "P", "RGB", "RGBA"],
    ),
    "JPEG": FormatInfo(
        canonical_name="JPEG",
        extensions=[".jpg", ".jpeg", ".jpe", ".jfif", ".jif", ".jfi"],
        mime_type="image/jpeg",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=False,
        supports_quality=True,
        pillow_format="JPEG",
        description="Joint Photographic Experts Group",
        allowed_modes=["L", "RGB", "CMYK"],
    ),
    "WEBP": FormatInfo(
        canonical_name="WEBP",
        extensions=[".webp"],
        mime_type="image/webp",
        backend="pillow",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=True,
        pillow_format="WEBP",
        description="WebP Image Format",
        allowed_modes=["RGB", "RGBA"],
    ),
    "GIF": FormatInfo(
        canonical_name="GIF",
        extensions=[".gif"],
        mime_type="image/gif",
        backend="pillow",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="GIF",
        description="Graphics Interchange Format",
        allowed_modes=["P", "L"],
    ),
    "BMP": FormatInfo(
        canonical_name="BMP",
        extensions=[".bmp", ".dib"],
        mime_type="image/bmp",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="BMP",
        description="Bitmap Image",
        allowed_modes=["1", "L", "P", "RGB"],
    ),
    "TIFF": FormatInfo(
        canonical_name="TIFF",
        extensions=[".tiff", ".tif"],
        mime_type="image/tiff",
        backend="pillow",
        supports_alpha=True,
        supports_animation=True,  # Multi-page
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=True,
        pillow_format="TIFF",
        description="Tagged Image File Format",
        allowed_modes=["1", "L", "LA", "P", "RGB", "RGBA", "CMYK"],
    ),
    "ICO": FormatInfo(
        canonical_name="ICO",
        extensions=[".ico"],
        mime_type="image/x-icon",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="ICO",
        description="Windows Icon Format",
        allowed_modes=["1", "L", "P", "RGBA", "RGB"],
    ),
    "CUR": FormatInfo(
        canonical_name="CUR",
        extensions=[".cur"],
        mime_type="image/x-win-bitmap",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="ICO",
        description="Windows Cursor Format",
        allowed_modes=["1", "L", "P", "RGBA", "RGB"],
    ),
    "TGA": FormatInfo(
        canonical_name="TGA",
        extensions=[".tga", ".icb", ".vda", ".vst"],
        mime_type="image/x-tga",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="TGA",
        description="Truevision Targa Graphic",
        allowed_modes=["L", "LA", "RGB", "RGBA"],
    ),
    "DDS": FormatInfo(
        canonical_name="DDS",
        extensions=[".dds"],
        mime_type="image/x-dds",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=False,
        supports_quality=False,
        pillow_format="DDS",
        imagemagick_format="DDS",
        description="DirectDraw Surface",
        allowed_modes=["RGB", "RGBA"],
    ),
    "PPM": FormatInfo(
        canonical_name="PPM",
        extensions=[".ppm"],
        mime_type="image/x-portable-pixmap",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PPM",
        description="Portable Pixmap Format",
        allowed_modes=["RGB"],
    ),
    "PGM": FormatInfo(
        canonical_name="PGM",
        extensions=[".pgm"],
        mime_type="image/x-portable-graymap",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PPM",
        description="Portable Graymap Format",
        allowed_modes=["L"],
    ),
    "PBM": FormatInfo(
        canonical_name="PBM",
        extensions=[".pbm"],
        mime_type="image/x-portable-bitmap",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PPM",
        description="Portable Bitmap Format",
        allowed_modes=["1"],
    ),
    "PNM": FormatInfo(
        canonical_name="PNM",
        extensions=[".pnm"],
        mime_type="image/x-portable-anymap",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PPM",
        description="Portable Anymap Format",
        allowed_modes=["1", "L", "RGB"],
    ),
    "PCX": FormatInfo(
        canonical_name="PCX",
        extensions=[".pcx"],
        mime_type="image/x-pcx",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PCX",
        description="Personal Computer Exchange",
        allowed_modes=["1", "L", "P", "RGB"],
    ),
    "SGI": FormatInfo(
        canonical_name="SGI",
        extensions=[".sgi", ".rgb", ".bw"],
        mime_type="image/sgi",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="SGI",
        description="Silicon Graphics Image",
        allowed_modes=["L", "RGB", "RGBA"],
    ),
    "XBM": FormatInfo(
        canonical_name="XBM",
        extensions=[".xbm"],
        mime_type="image/x-xbitmap",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="XBM",
        description="X BitMap Format",
        allowed_modes=["1"],
    ),
    "PALM": FormatInfo(
        canonical_name="PALM",
        extensions=[".palm"],
        mime_type="image/x-palm",
        backend="pillow",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        supports_quality=False,
        pillow_format="PALM",
        description="Palm Pixmap Format",
        allowed_modes=["P", "1"],
    ),
    "JP2": FormatInfo(
        canonical_name="JP2",
        extensions=[".jp2", ".j2k", ".jpc", ".jpf", ".jpx"],
        mime_type="image/jp2",
        backend="pillow",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=True,
        pillow_format="JPEG2000",
        description="JPEG 2000 Format",
        allowed_modes=["L", "LA", "RGB", "RGBA"],
    ),

    # --- SVG Vector Format ---
    "SVG": FormatInfo(
        canonical_name="SVG",
        extensions=[".svg"],
        mime_type="image/svg+xml",
        backend="svg",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=False,
        description="Scalable Vector Graphics",
    ),

    # --- Advanced Formats Handled by ImageMagick (or Plugins) ---
    "PSD": FormatInfo(
        canonical_name="PSD",
        extensions=[".psd"],
        mime_type="image/vnd.adobe.photoshop",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        imagemagick_format="PSD",
        description="Adobe Photoshop Document",
        delegate_needed="ImageMagick",
    ),
    "HEIC": FormatInfo(
        canonical_name="HEIC",
        extensions=[".heic"],
        mime_type="image/heic",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=True,
        supports_lossless=False,
        supports_quality=True,
        imagemagick_format="HEIC",
        description="High Efficiency Image Coding",
        delegate_needed="libheif / pillow-heif",
    ),
    "HEIF": FormatInfo(
        canonical_name="HEIF",
        extensions=[".heif"],
        mime_type="image/heif",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=True,
        supports_lossless=False,
        supports_quality=True,
        imagemagick_format="HEIF",
        description="High Efficiency Image Format",
        delegate_needed="libheif / pillow-heif",
    ),
    "AVIF": FormatInfo(
        canonical_name="AVIF",
        extensions=[".avif"],
        mime_type="image/avif",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=True,
        supports_lossless=True,
        supports_quality=True,
        imagemagick_format="AVIF",
        description="AV1 Image File Format",
        delegate_needed="libheif / libavif / pillow-avif-plugin",
    ),
    "HDR": FormatInfo(
        canonical_name="HDR",
        extensions=[".hdr"],
        mime_type="image/vnd.radiance",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=False,
        imagemagick_format="HDR",
        description="Radiance High Dynamic Range",
        delegate_needed="ImageMagick",
    ),
    "EXR": FormatInfo(
        canonical_name="EXR",
        extensions=[".exr"],
        mime_type="image/x-exr",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        imagemagick_format="EXR",
        description="OpenEXR High Dynamic Range",
        delegate_needed="OpenEXR delegate for ImageMagick",
    ),
    "WBMP": FormatInfo(
        canonical_name="WBMP",
        extensions=[".wbmp"],
        mime_type="image/vnd.wap.wbmp",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="WBMP",
        description="Wireless Application Protocol Bitmap",
        delegate_needed="ImageMagick",
    ),
    "JBIG": FormatInfo(
        canonical_name="JBIG",
        extensions=[".jbig", ".jbg"],
        mime_type="image/x-jbig",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="JBIG",
        description="Joint Bi-level Image Experts Group",
        delegate_needed="JBIGkit delegate for ImageMagick",
    ),
    "MAP": FormatInfo(
        canonical_name="MAP",
        extensions=[".map"],
        mime_type="image/x-map",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="MAP",
        description="Colormap intensities and indices",
        delegate_needed="ImageMagick",
    ),
    "PDB": FormatInfo(
        canonical_name="PDB",
        extensions=[".pdb"],
        mime_type="image/x-pdb",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PDB",
        description="Palm Database ImageViewer format",
        delegate_needed="ImageMagick",
    ),
    "XPM": FormatInfo(
        canonical_name="XPM",
        extensions=[".xpm"],
        mime_type="image/x-xpixmap",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="XPM",
        description="X PixMap Format",
        delegate_needed="ImageMagick",
    ),
    "JPS": FormatInfo(
        canonical_name="JPS",
        extensions=[".jps"],
        mime_type="image/x-jps",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=False,
        imagemagick_format="JPS",
        description="JPEG Stereo Image",
        delegate_needed="ImageMagick",
    ),
    "SUN": FormatInfo(
        canonical_name="SUN",
        extensions=[".sun", ".ras", ".rs"],
        mime_type="image/x-sun-raster",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="SUN",
        description="Sun Raster Image",
        delegate_needed="ImageMagick",
    ),
    "RGB": FormatInfo(
        canonical_name="RGB",
        extensions=[".rgb"],
        mime_type="image/x-rgb",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="RGB",
        description="Raw Red, Green, Blue bytes",
        delegate_needed="ImageMagick",
    ),
    "RGBA": FormatInfo(
        canonical_name="RGBA",
        extensions=[".rgba"],
        mime_type="image/x-rgba",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="RGBA",
        description="Raw Red, Green, Blue, Alpha bytes",
        delegate_needed="ImageMagick",
    ),
    "RGBO": FormatInfo(
        canonical_name="RGBO",
        extensions=[".rgbo"],
        mime_type="image/x-rgbo",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="RGBO",
        description="Raw Red, Green, Blue, Opacity bytes",
        delegate_needed="ImageMagick",
    ),
    "PICT": FormatInfo(
        canonical_name="PICT",
        extensions=[".pct", ".pict"],
        mime_type="image/x-pict",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PICT",
        description="Apple Macintosh QuickDraw Picture",
        delegate_needed="ImageMagick",
    ),
    "FAX": FormatInfo(
        canonical_name="FAX",
        extensions=[".fax"],
        mime_type="image/g3fax",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="FAX",
        description="CCITT Group 3 FAX format",
        delegate_needed="ImageMagick",
    ),
    "G3": FormatInfo(
        canonical_name="G3",
        extensions=[".g3"],
        mime_type="image/g3fax",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="G3",
        description="CCITT Group 3 Fax Format",
        delegate_needed="ImageMagick",
    ),
    "G4": FormatInfo(
        canonical_name="G4",
        extensions=[".g4"],
        mime_type="image/g4fax",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="G4",
        description="CCITT Group 4 Fax Format",
        delegate_needed="ImageMagick",
    ),
    "PICON": FormatInfo(
        canonical_name="PICON",
        extensions=[".picon"],
        mime_type="image/x-picon",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PICON",
        description="Personal Icon Format",
        delegate_needed="ImageMagick",
    ),
    "SIXEL": FormatInfo(
        canonical_name="SIXEL",
        extensions=[".sixel", ".six"],
        mime_type="image/x-sixel",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="SIXEL",
        description="DEC Sixel Graphics Format",
        delegate_needed="ImageMagick",
    ),
    "PCD": FormatInfo(
        canonical_name="PCD",
        extensions=[".pcd"],
        mime_type="image/x-photo-cd",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=False,
        imagemagick_format="PCD",
        description="Kodak Photo CD Format",
        delegate_needed="ImageMagick",
    ),
    "MNG": FormatInfo(
        canonical_name="MNG",
        extensions=[".mng"],
        mime_type="video/x-mng",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=True,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="MNG",
        description="Multiple-image Network Graphics",
        delegate_needed="ImageMagick",
    ),
    "YUV": FormatInfo(
        canonical_name="YUV",
        extensions=[".yuv"],
        mime_type="image/x-yuv",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=False,
        imagemagick_format="YUV",
        description="CCIR 601 4:1:1 or 4:2:2 raw bytes",
        delegate_needed="ImageMagick",
    ),
    "UYVY": FormatInfo(
        canonical_name="UYVY",
        extensions=[".uyvy"],
        mime_type="image/x-uyvy",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=False,
        imagemagick_format="UYVY",
        description="16-bit YUV 4:2:2 Format",
        delegate_needed="ImageMagick",
    ),
    "PGX": FormatInfo(
        canonical_name="PGX",
        extensions=[".pgx"],
        mime_type="image/x-pgx",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PGX",
        description="JPEG 2000 VM format",
        delegate_needed="ImageMagick",
    ),
    "HRZ": FormatInfo(
        canonical_name="HRZ",
        extensions=[".hrz"],
        mime_type="image/x-hrz",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="HRZ",
        description="Slow Scan TeleVision Format",
        delegate_needed="ImageMagick",
    ),
    "IPL": FormatInfo(
        canonical_name="IPL",
        extensions=[".ipl"],
        mime_type="image/x-ipl",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="IPL",
        description="IPL Image Format",
        delegate_needed="ImageMagick",
    ),
    "PAM": FormatInfo(
        canonical_name="PAM",
        extensions=[".pam"],
        mime_type="image/x-portable-arbitrarymap",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PAM",
        description="Portable Arbitrary Map Format",
        delegate_needed="ImageMagick",
    ),
    "OTB": FormatInfo(
        canonical_name="OTB",
        extensions=[".otb"],
        mime_type="image/x-otb",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="OTB",
        description="On-the-air bitmap",
        delegate_needed="ImageMagick",
    ),
    "PFM": FormatInfo(
        canonical_name="PFM",
        extensions=[".pfm"],
        mime_type="image/x-pfm",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PFM",
        description="Portable Float Map",
        delegate_needed="ImageMagick",
    ),
    "RGF": FormatInfo(
        canonical_name="RGF",
        extensions=[".rgf"],
        mime_type="image/x-rgf",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="RGF",
        description="LEGO Mindstorms EV3 Robot Graphic",
        delegate_needed="ImageMagick",
    ),
    "VIPS": FormatInfo(
        canonical_name="VIPS",
        extensions=[".vips", ".v"],
        mime_type="image/x-vips",
        backend="imagemagick",
        supports_alpha=True,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        imagemagick_format="VIPS",
        description="VIPS Image Processing System Format",
        delegate_needed="ImageMagick",
    ),
    "PAL": FormatInfo(
        canonical_name="PAL",
        extensions=[".pal"],
        mime_type="image/x-pal",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="PAL",
        description="16-bit color PAL format",
        delegate_needed="ImageMagick",
    ),
    "XWD": FormatInfo(
        canonical_name="XWD",
        extensions=[".xwd"],
        mime_type="image/x-xwindowdump",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="XWD",
        description="X Window Dump",
        delegate_needed="ImageMagick",
    ),
    "FITS": FormatInfo(
        canonical_name="FITS",
        extensions=[".fts", ".fits"],
        mime_type="image/fits",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=True,
        supports_lossless=True,
        imagemagick_format="FITS",
        description="Flexible Image Transport System",
        delegate_needed="ImageMagick",
    ),
    "VIFF": FormatInfo(
        canonical_name="VIFF",
        extensions=[".viff", ".xv"],
        mime_type="image/x-viff",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="VIFF",
        description="Khoros Visualization Image File",
        delegate_needed="ImageMagick",
    ),
    "MTV": FormatInfo(
        canonical_name="MTV",
        extensions=[".mtv"],
        mime_type="image/x-mtv",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="MTV",
        description="MTV Raytracing Format",
        delegate_needed="ImageMagick",
    ),
    "XV": FormatInfo(
        canonical_name="XV",
        extensions=[".xv"],
        mime_type="image/x-xv",
        backend="imagemagick",
        supports_alpha=False,
        supports_animation=False,
        supports_metadata=False,
        supports_lossless=True,
        imagemagick_format="XV",
        description="Khoros / XV Visual Schnauzer thumbnail",
        delegate_needed="ImageMagick",
    ),
}

# Alias mapping: maps common extensions and aliases to canonical names
FORMAT_ALIASES: Dict[str, str] = {
    # JPEG variants
    "jpg": "JPEG",
    "jpeg": "JPEG",
    "jpe": "JPEG",
    "jfif": "JPEG",
    "jif": "JPEG",
    "jfi": "JPEG",
    # TIFF variants
    "tif": "TIFF",
    "tiff": "TIFF",
    # WEBP
    "webp": "WEBP",
    # PNG
    "png": "PNG",
    "apng": "PNG",
    # GIF
    "gif": "GIF",
    # BMP
    "bmp": "BMP",
    "dib": "BMP",
    # SVG
    "svg": "SVG",
    "svgz": "SVG",
    # ICO / CUR
    "ico": "ICO",
    "cur": "CUR",
    # TGA
    "tga": "TGA",
    "icb": "TGA",
    "vda": "TGA",
    "vst": "TGA",
    # DDS
    "dds": "DDS",
    # Netpbm
    "ppm": "PPM",
    "pgm": "PGM",
    "pbm": "PBM",
    "pnm": "PNM",
    "pam": "PAM",
    # PCX
    "pcx": "PCX",
    # SGI
    "sgi": "SGI",
    "bw": "SGI",
    # XBM / XPM
    "xbm": "XBM",
    "xpm": "XPM",
    # PALM
    "palm": "PALM",
    # JP2
    "jp2": "JP2",
    "j2k": "JP2",
    "jpc": "JP2",
    "jpf": "JP2",
    "jpx": "JP2",
    # Photoshop
    "psd": "PSD",
    # HEIC / HEIF
    "heic": "HEIC",
    "heif": "HEIF",
    # AVIF
    "avif": "AVIF",
    # Radiance & OpenEXR
    "hdr": "HDR",
    "exr": "EXR",
    # JBIG
    "jbig": "JBIG",
    "jbg": "JBIG",
    # WBMP
    "wbmp": "WBMP",
    # Sun / Raster
    "sun": "SUN",
    "ras": "SUN",
    "rs": "SUN",
    # PICT
    "pct": "PICT",
    "pict": "PICT",
    # Raw pixels
    "rgb": "RGB",
    "rgba": "RGBA",
    "rgbo": "RGBO",
    # Fax
    "fax": "FAX",
    "g3": "G3",
    "g4": "G4",
    # Sixel
    "sixel": "SIXEL",
    "six": "SIXEL",
    # Other legacy & scientific
    "picon": "PICON",
    "pcd": "PCD",
    "mng": "MNG",
    "yuv": "YUV",
    "uyvy": "UYVY",
    "pgx": "PGX",
    "hrz": "HRZ",
    "ipl": "IPL",
    "otb": "OTB",
    "pfm": "PFM",
    "rgf": "RGF",
    "vips": "VIPS",
    "pal": "PAL",
    "xwd": "XWD",
    "fts": "FITS",
    "fits": "FITS",
    "viff": "VIFF",
    "mtv": "MTV",
    "xv": "XV",
    "map": "MAP",
    "pdb": "PDB",
    "jps": "JPS",
}


def normalize_format(format_name: str) -> str:
    """Normalize a format name or file extension into its canonical uppercase format."""
    if not format_name or not isinstance(format_name, str):
        raise UnsupportedFormatError(
            str(format_name), "Invalid format name specified."
        )

    clean = format_name.strip().lower()
    if clean.startswith("."):
        clean = clean[1:]

    # Check alias map
    if clean in FORMAT_ALIASES:
        return FORMAT_ALIASES[clean]

    # Check uppercase directly in registry
    upper = clean.upper()
    if upper in FORMAT_REGISTRY:
        return upper

    # Not recognized
    raise UnsupportedFormatError(
        format_name=format_name,
        supported_formats=list(FORMAT_REGISTRY.keys()),
    )


def get_format_info(format_name: str) -> FormatInfo:
    """Get the FormatInfo definition for a given format name or extension."""
    canonical = normalize_format(format_name)
    return FORMAT_REGISTRY[canonical]


def get_primary_extension(canonical_format: str) -> str:
    """Get default primary file extension (including leading dot) for canonical format."""
    info = get_format_info(canonical_format)
    return info.extensions[0]

