"""SVG generation backend: raster embedding and vectorization."""

import base64
import io
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, List, Optional
from PIL import Image

from image_converter.backends.base import BaseBackend
from image_converter.exceptions import (
    ConversionError,
    MissingDependencyError,
)
from image_converter.models import ConversionResult, FormatInfo
from image_converter.security import (
    atomic_output_file,
    validate_image_dimensions,
)


class SVGBackend(BaseBackend):
    """Backend for converting raster images to SVG."""

    @property
    def name(self) -> str:
        return "svg"

    def is_available(self) -> bool:
        return True

    def can_handle_output(self, format_info: FormatInfo) -> bool:
        return format_info.canonical_name == "SVG"

    def _convert_embedded_raster(
        self,
        input_path: Path,
        output_path: Path,
        options: Dict[str, Any],
    ) -> ConversionResult:
        start_time = time.time()
        warnings: List[str] = [
            "Generated embedded raster SVG (not vector traced). Set vectorize=True for vector contour tracing."
        ]

        with Image.open(input_path) as img:
            width, height = img.size
            validate_image_dimensions((width, height))
            src_format = img.format or "PNG"

            buf = io.BytesIO()
            has_alpha = img.mode in ("RGBA", "LA", "PA") or "transparency" in img.info
            if has_alpha:
                img.save(buf, format="PNG")
                mime_type = "image/png"
            else:
                img.save(buf, format="JPEG", quality=int(options.get("quality", 92)))
                mime_type = "image/jpeg"

            b64_data = base64.b64encode(buf.getvalue()).decode("ascii")

        svg_content = (
            f'<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<!-- Generated by ImageConverter: Embedded Raster SVG -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'xmlns:xlink="http://www.w3.org/1999/xlink" '
            f'width="{width}" height="{height}" viewBox="0 0 {width} {height}" version="1.1">\n'
            f'  <image width="{width}" height="{height}" href="data:{mime_type};base64,{b64_data}"/>\n'
            f'</svg>\n'
        )

        with atomic_output_file(output_path, suffix=".svg") as tmp_target:
            tmp_target.write_text(svg_content, encoding="utf-8")

        file_size = output_path.stat().st_size
        elapsed = (time.time() - start_time) * 1000.0

        return ConversionResult(
            success=True,
            input_path=str(input_path),
            output_path=str(output_path),
            input_format=src_format,
            output_format="SVG",
            backend_used=self.name,
            file_size_bytes=file_size,
            dimensions=(width, height),
            color_mode="SVG",
            has_transparency=has_alpha,
            is_animated=False,
            frame_count=1,
            duration_ms=round(elapsed, 2),
            metadata_preserved=True,
            warnings=warnings,
        )

    def _convert_vectorize(
        self,
        input_path: Path,
        output_path: Path,
        options: Dict[str, Any],
    ) -> ConversionResult:
        potrace_bin = shutil.which("potrace")
        autotrace_bin = shutil.which("autotrace")

        if not potrace_bin and not autotrace_bin:
            raise MissingDependencyError(
                dependency_name="potrace or autotrace",
                format_name="SVG (vectorize=True)",
                installation_instructions=(
                    "True vectorization requires a vector tracing utility. "
                    "Install potrace ('sudo apt-get install potrace' on Debian/Ubuntu, "
                    "'brew install potrace' on macOS) or autotrace."
                ),
            )

        start_time = time.time()
        with Image.open(input_path) as img:
            width, height = img.size
            bmp_buf = io.BytesIO()
            mono = img.convert("L").point(lambda x: 0 if x < 128 else 255, "1")
            mono.save(bmp_buf, format="BMP")
            bmp_bytes = bmp_buf.getvalue()

        with atomic_output_file(output_path, suffix=".svg") as tmp_target:
            if potrace_bin:
                proc = subprocess.run(
                    [potrace_bin, "-s", "-o", str(tmp_target)],
                    input=bmp_bytes,
                    capture_output=True,
                    timeout=30,
                    check=False,
                )
                if proc.returncode != 0:
                    raise ConversionError(
                        f"potrace vectorization failed: {proc.stderr.decode('utf-8', errors='ignore')}"
                    )
            elif autotrace_bin:
                proc = subprocess.run(
                    [autotrace_bin, "--output-format", "svg", "--output-file", str(tmp_target)],
                    input=bmp_bytes,
                    capture_output=True,
                    timeout=30,
                    check=False,
                )
                if proc.returncode != 0:
                    raise ConversionError(
                        f"autotrace vectorization failed: {proc.stderr.decode('utf-8', errors='ignore')}"
                    )

        file_size = output_path.stat().st_size
        elapsed = (time.time() - start_time) * 1000.0

        return ConversionResult(
            success=True,
            input_path=str(input_path),
            output_path=str(output_path),
            input_format=str(input_path.suffix).lstrip(".").upper(),
            output_format="SVG",
            backend_used=f"{self.name} (vectorized)",
            file_size_bytes=file_size,
            dimensions=(width, height),
            color_mode="VECTOR",
            has_transparency=True,
            is_animated=False,
            frame_count=1,
            duration_ms=round(elapsed, 2),
            metadata_preserved=False,
            warnings=["Image vectorized using contour tracing."],
        )

    def convert(
        self,
        input_path: Path,
        output_path: Path,
        target_format: str,
        options: Dict[str, Any],
    ) -> ConversionResult:
        vectorize = options.get("vectorize", False)
        if vectorize:
            return self._convert_vectorize(input_path, output_path, options)
        return self._convert_embedded_raster(input_path, output_path, options)

